# За чист URLs, sitemap и minification
permalink: /:basename/

# Включване на специални файлове
include:
  - ai-plugin.json
  - .well-known
  - llms.txt
  - robots.txt
  - 404.html

exclude:
  - wordpress
  - README.md

sass:
  style: compressed
